(node:21) ExperimentalWarning: CommonJS module /home/container/tmp/node-v23.1.0-linux-x64/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /home/container/tmp/node-v23.1.0-linux-x64/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

up to date, audited 167 packages in 1s

27 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> discord-bot@1.0.0 start
> node index.js

[32minfo[39m: تم تحميل الأمر: admin-data {"timestamp":"2025-01-19T10:33:35.426Z"}
[32minfo[39m: تم تحميل الأمر: help {"timestamp":"2025-01-19T10:33:35.429Z"}
[32minfo[39m: تم تحميل الأمر: open-sessions {"timestamp":"2025-01-19T10:33:35.430Z"}
[32minfo[39m: تم تحميل الأمر: ping {"timestamp":"2025-01-19T10:33:35.431Z"}
[32minfo[39m: تم تحميل الأمر: servers-list {"timestamp":"2025-01-19T10:33:35.431Z"}
[32minfo[39m: تم تحميل الأمر: setup {"timestamp":"2025-01-19T10:33:35.434Z"}
[32minfo[39m: تم تحميل الأمر: update {"timestamp":"2025-01-19T10:33:35.434Z"}
فشل في تسجيل الدخول (محاولة 1/5): Error [TokenInvalid]: An invalid token was provided.
    at Client.login (/home/container/node_modules/discord.js/src/client/Client.js:216:52)
    at loginWithRetry (/home/container/index.js:1269:26)
    at Object.<anonymous> (/home/container/index.js:1286:1)
    at Module._compile (node:internal/modules/cjs/loader:1572:14)
    at Object..js (node:internal/modules/cjs/loader:1709:10)
    at Module.load (node:internal/modules/cjs/loader:1315:32)
    at Function._load (node:internal/modules/cjs/loader:1125:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5) {
  code: 'TokenInvalid'
}
[31merror[39m: خطأ في الاتصال بقاعدة البيانات: خطأ في الاتصال بقاعدة البيانات: {"critical":true,"stack":"MongooseError: The `uri` parameter to `openUri()` must be a string, got \"undefined\". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.\n    at NativeConnection.createClient (/home/container/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:225:11)\n    at NativeConnection.openUri (/home/container/node_modules/mongoose/lib/connection.js:835:34)\n    at Mongoose.connect (/home/container/node_modules/mongoose/lib/mongoose.js:447:15)\n    at Object.<anonymous> (/home/container/index.js:240:10)\n    at Module._compile (node:internal/modules/cjs/loader:1572:14)\n    at Object..js (node:internal/modules/cjs/loader:1709:10)\n    at Module.load (node:internal/modules/cjs/loader:1315:32)\n    at Function._load (node:internal/modules/cjs/loader:1125:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)","timestamp":"2025-01-19T10:33:35.439Z"}
